server-ip=127.0.0.1
server-port=25565
online-mode=false
view-distance=2
simulation-distance=2
level-type=minecraft:flat
generate-structures=false
generator-settings={"biome":"minecraft:plains","layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"structure_overrides":[]}
